# Generated by Django 2.1.1 on 2018-10-02 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("noauth", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="code_last_sent",
            field=models.DateTimeField(blank=True, null=True),
        )
    ]
