# Generated by Django 2.1.2 on 2018-10-19 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("districts", "0004_district_slug"),
        ("noauth", "0002_user_code_last_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="building",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="districts.Building",
            ),
            preserve_default=False,
        )
    ]
