# Generated by Django 2.1.2 on 2018-10-07 14:59

from django.db import migrations, models

import items.models


class Migration(migrations.Migration):

    dependencies = [("items", "0002_auto_20181007_1451")]

    operations = [
        migrations.AlterField(
            model_name="itemimage",
            name="image",
            field=models.ImageField(height_field="height", width_field="width"),
        )
    ]
