# Generated by Django 2.1.2 on 2018-10-07 15:42

from django.db import migrations, models

import items.models


class Migration(migrations.Migration):

    dependencies = [("items", "0003_auto_20181007_1459")]

    operations = [
        migrations.RenameField(
            model_name="itemimage", old_name="height", new_name="full_size_height"
        ),
        migrations.RenameField(
            model_name="itemimage", old_name="width", new_name="full_size_width"
        ),
        migrations.AlterField(
            model_name="itemimage",
            name="image",
            field=models.ImageField(
                height_field="full_size_height", width_field="full_size_width"
            ),
        ),
    ]
