# Generated by Django 2.1.2 on 2018-10-07 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("items", "0005_itemimage_thumbnail_sizes")]

    operations = [
        migrations.AlterField(
            model_name="itemimage",
            name="full_size_height",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="itemimage",
            name="full_size_width",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
