# Generated by Django 2.1.2 on 2018-10-08 01:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("items", "0006_auto_20181007_2134")]

    operations = [
        migrations.AlterField(
            model_name="itemimage", name="image", field=models.ImageField(upload_to="")
        ),
        migrations.AlterField(
            model_name="itemimage",
            name="thumbnail_sizes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.SmallIntegerField(), blank=True, null=True, size=None
            ),
        ),
    ]
