# Generated by Django 2.1.2 on 2018-10-08 03:04

from django.db import migrations, models

import items.models


class Migration(migrations.Migration):

    dependencies = [("items", "0007_auto_20181008_0146")]

    operations = [
        migrations.AlterField(
            model_name="itemimage",
            name="image",
            field=models.ImageField(upload_to=items.models.generate_file_path),
        )
    ]
