# Generated by Django 2.1.2 on 2018-10-09 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("items", "0008_auto_20181008_0304")]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="slug",
            field=models.SlugField(max_length=60, unique=True),
        )
    ]
