# Generated by Django 2.1.2 on 2018-10-26 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("items", "0011_auto_20181019_2228")]

    operations = [migrations.RemoveField(model_name="item", name="deleted")]
