# Generated by Django 2.1.2 on 2018-10-04 02:01

import localflavor.us.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("districts", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="building",
            name="city",
            field=models.CharField(default="None", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="building",
            name="postal_code",
            field=localflavor.us.models.USZipCodeField(default=12345, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="building",
            name="state",
            field=localflavor.us.models.USStateField(default="KY", max_length=2),
            preserve_default=False,
        ),
    ]
