# Generated by Django 2.1.2 on 2018-10-04 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("districts", "0002_auto_20181004_0201")]

    operations = [
        migrations.AddField(
            model_name="building",
            name="slug",
            field=models.SlugField(default="No"),
            preserve_default=False,
        )
    ]
